import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ErrorTest0 {

    public static boolean debug = false;

    @Test
    public void test01() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test01");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) '4');
    }

    @Test
    public void test02() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test02");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) 'a');
    }

    @Test
    public void test03() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test03");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (byte) 10);
    }

    @Test
    public void test04() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test04");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (short) 100);
    }

    @Test
    public void test05() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test05");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp(1);
    }

    @Test
    public void test06() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test06");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp(0);
    }

    @Test
    public void test07() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test07");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (byte) -1);
    }

    @Test
    public void test08() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test08");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) ' ');
    }

    @Test
    public void test09() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test09");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((-1));
    }

    @Test
    public void test10() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test10");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (byte) 100);
    }

    @Test
    public void test11() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test11");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp(100);
    }

    @Test
    public void test12() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test12");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (byte) 0);
    }

    @Test
    public void test13() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test13");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (short) 10);
    }

    @Test
    public void test14() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test14");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (byte) 1);
    }

    @Test
    public void test15() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test15");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (short) -1);
    }

    @Test
    public void test16() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test16");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (short) 0);
    }

    @Test
    public void test17() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test17");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) (short) 1);
    }

    @Test
    public void test18() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test18");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp((int) '#');
    }

    @Test
    public void test19() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "ErrorTest0.test19");
        DevideByZero devideByZero0 = new DevideByZero();
        // during test generation this statement threw an exception of type java.lang.ArithmeticException in error
        int int2 = devideByZero0.devideByZerp(10);
    }
}

